<?php

namespace iflow\native\Window\Electron\Layout\Menu\Options;

class TrayOptions extends MenuOptions {

    public string $pressedIcon;

    public string $title;

    public string $tipTitle;

    public array $hideFields = [ 'menuItems' ];

    public function toArray(array $options = []): array {
        $options['menu'] = $this->getMenuItemsToArray();
        return parent::toArray($options); // TODO: Change the autogenerated stub
    }
}
